// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeBWWDd3Ei8qu8Rj17vkRv7w24zuRnfGg',
    appId: '1:853135729772:web:740424302cf6e007b7a449',
    messagingSenderId: '853135729772',
    projectId: 'legalaid-2104d',
    authDomain: 'legalaid-2104d.firebaseapp.com',
    databaseURL: 'https://legalaid-2104d-default-rtdb.firebaseio.com',
    storageBucket: 'legalaid-2104d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4pnJM4C9vzfxBWr-34cCAYZdRRl18SLg',
    appId: '1:853135729772:android:ab72a1fb2a7c8e89b7a449',
    messagingSenderId: '853135729772',
    projectId: 'legalaid-2104d',
    databaseURL: 'https://legalaid-2104d-default-rtdb.firebaseio.com',
    storageBucket: 'legalaid-2104d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgkyPg8J_NKOkOku88QvMLQtxasJCQLJ0',
    appId: '1:853135729772:ios:50050badbb7c4e84b7a449',
    messagingSenderId: '853135729772',
    projectId: 'legalaid-2104d',
    databaseURL: 'https://legalaid-2104d-default-rtdb.firebaseio.com',
    storageBucket: 'legalaid-2104d.appspot.com',
    androidClientId: '853135729772-rrq3bg91ff9rfin50k3djho590pdf0po.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgkyPg8J_NKOkOku88QvMLQtxasJCQLJ0',
    appId: '1:853135729772:ios:50050badbb7c4e84b7a449',
    messagingSenderId: '853135729772',
    projectId: 'legalaid-2104d',
    databaseURL: 'https://legalaid-2104d-default-rtdb.firebaseio.com',
    storageBucket: 'legalaid-2104d.appspot.com',
    androidClientId: '853135729772-rrq3bg91ff9rfin50k3djho590pdf0po.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );
}
